ems/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", view=views.home_page),
    path("employee/", include("website.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.text import slugify


class Employee(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    slug = models.SlugField(unique=True, blank=True)
    picture = models.ImageField(default="default.png")
    emp_id = models.PositiveIntegerField(primary_key=True)
    email = models.EmailField(unique=True)
    phone = models.CharField(max_length=20)
    age = models.PositiveIntegerField()
    address = models.TextField()
    FULL_TIME_CHOICES = [
        ("Yes", "Yes"),
        ("No", "No"),
    ]
    full_time = models.CharField(max_length=3, choices=FULL_TIME_CHOICES)
    designation = models.CharField(max_length=100)
    salary = models.PositiveIntegerField()

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        super().save(*args, **kwargs)

    def __str__(self):
        return self.name

templates/partials/footer.html
<footer
  class="pt-3 mt-5 bg-white container text-body-secondary text-center border-top"
>
  &copy; Ankit Jain 2024
</footer>

templates/partials/navbar.html
<header
  class="pb-3 mb-4 border-bottom d-flex justify-content-between align-items-center bg-white"
>
  <a href="/" class="d-flex align-items-center text-dark text-decoration-none">
    <span class="fs-4">EmployEase</span>
  </a>
  <div class="d-flex align-items-center">
    {% if value %} {% if user.is_authenticated %}
    <span class="me-3 d-none d-sm-inline"
      >Welcome <span class="fw-bold">{{user.username}}</span></span
    >
    {% endif %}
    <a
      href="/employee/{% if user.is_authenticated %}logout{% else %}{% block url %}login{% endblock %}{% endif %}/"
      ><button class="btn btn-warning me-3">
        {% if user.is_authenticated %} Logout {% else %} {% block data %} Login
        {% endblock %} {% endif %}
      </button></a
    >
    {% endif %} {% if perms.website.add_employee %}
    <a href="/employee/add/"
      ><button class="btn btn-success">Add Employee</button></a
    >
    {% endif %}
  </div>
</header>