ems/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", view=views.home_page),
    path("employee/", include("website.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.text import slugify


class Employee(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    slug = models.SlugField(unique=True, blank=True)
    picture = models.ImageField(default="default.png")
    emp_id = models.PositiveIntegerField(primary_key=True)
    email = models.EmailField(unique=True)
    phone = models.CharField(max_length=20)
    age = models.PositiveIntegerField()
    address = models.TextField()
    FULL_TIME_CHOICES = [
        ("Yes", "Yes"),
        ("No", "No"),
    ]
    full_time = models.CharField(max_length=3, choices=FULL_TIME_CHOICES)
    designation = models.CharField(max_length=100)
    salary = models.PositiveIntegerField()

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        super().save(*args, **kwargs)

    def __str__(self):
        return self.name

ems/views.py
from django.shortcuts import render


def home_page(request):
    return render(request, "home.html", {"value": False})

templates/ems/create.html
{% extends "base/base.html" %} {% block title %}
<title>EmployEase | Create a Employee</title>
{% endblock title %} {% block content %}
<div class="container py-4">
  {% include "partials/navbar.html" %}
  <form enctype="multipart/form-data" method="post">
    {% csrf_token %} {{ form.as_p }}
    <button type="submit" class="btn btn-info">Add Employee</button>
  </form>
  {% include "partials/footer.html" %}
</div>
{% endblock content %}

templates/ems/home.html
{% extends "../base/base.html" %} 
{% load has_group %}
{% block title %}
<title>EmployEase | Employees</title>
{% endblock title %} 
{% block content %}
<div class="container py-4">
  {% include "partials/navbar.html" %}
  {% if employees|length > 0 %}
  <div class="table-responsive">
    <table class="table">
      <thead>
        <tr>
          <th scope="col">SNo</th>
          <th scope="col">Photo</th>
          <th scope="col">Name</th>
          <th scope="col">Designation</th>
          <th scope="col">Email</th>
          {% if perms.website.change_employee or perms.website.delete_employee %}
            <th scope="col">Actions</th>
          {% endif %}
        </tr>
      </thead>
      <tbody>
        {% for element in employees %}
        <tr>
          <th scope="row">{{ forloop.counter }}</th>
          <td>
            <div style="max-width: 100px" class="d-flex justify-content-center">
              <img
                src="/media/{{ element.picture }}"
                alt=""
                class="rounded-circle"
                style="width: 50%; height: 50%"
              />
            </div>
          </td>
          <td>{{ element.name }}</td>
          <td>{{ element.designation }}</td>
          <td>{{ element.email }}</td>
          {% if perms.website.change_employee or perms.website.delete_employee %}
          <td>
            <div class="d-flex align-items-center">
              <a href="/employee/update/{{ element.slug }}/"
                ><button class="btn btn-warning me-3">Update</button></a
              >
              <a href="/employee/delete/{{ element.emp_id }}/"
                ><button class="btn btn-danger me-3">Delete</button></a
              >
              {% if user.is_staff %} 
              {% if element.user|has_group:"moderator" %}
              <a href="/employee/mod/remove/{{ element.user.id }}/"
                ><button class="btn btn-dark me-3">Remove Mod</button></a
              >
              {% else %}
              <a href="/employee/mod/add/{{ element.user.id }}/"
                ><button class="btn btn-info me-3">Make Mod</button></a
              >
              {% endif %} 
            {% endif %}
            </div>
          </td>
          {% endif %}
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
  {% endif %} 
{% include "partials/footer.html" %}
</div>
{% endblock content %}

templates/ems/update.html
{% extends "base/base.html" %}

{% block title %}
<title>EmployEase | Update Employee</title>
{% endblock title %}

{% block content %}
<div class="container py-4">
  {% include "partials/navbar.html" %}
  <form class="row g-3" method="post">
    {% csrf_token %}
    <div class="col-12">
      <label for="name" class="form-label">Employee Name</label>
      <input type="text" class="form-control" id="name" name="name" placeholder="Enter employee name" value="{{ employee.name }}">
    </div>
    <div class="col-12">
      <label for="email" class="form-label">Employee Email</label>
      <input type="email" class="form-control" id="email" name="email" placeholder="Enter employee email" value="{{ employee.email }}">
    </div>
    <div class="col-12">
      <label for="phone" class="form-label">Employee Phone</label>
      <input type="text" class="form-control" id="phone" name="phone" placeholder="Enter employee phone" value="{{ employee.phone }}">
    </div>
    <div class="col-12">
      <label for="address" class="form-label">Employee Address</label>
      <input type="text" class="form-control" id="address" name="address" placeholder="Enter employee address" value="{{ employee.address }}">
    </div>
    <div class="col-12">
      <button type="submit" class="btn btn-primary">Update Employee</button>
    </div>
  </form>
  {% include "partials/footer.html" %}
</div>
{% endblock content %}